name: Test and Lint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web:
    name: Web (Next.js)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Type check
        run: npx tsc --noEmit
      - name: Lint (Next.js)
        run: npm run lint
      - name: Build
        run: npm run build

  python:
    name: Python (Serverless + FastAPI)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          # Root requirements (serverless functions)
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Local FastAPI dev server requirements
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
      - name: Syntax check (compileall)
        run: |
          python -m compileall -q api backend
      - name: Static checks (placeholder)
        if: false
        run: |
          echo "Add Ruff/Flake8 if adopted in the repo"
